services:
  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      QUOTESVC_DATABASE_HOST: db
      QUOTESVC_DATABASE_PORT: 5432
      QUOTESVC_DATABASE_USER: postgres
      QUOTESVC_DATABASE_PASSWORD: postgres
      QUOTESVC_DATABASE_NAME: quotesdb
      QUOTESVC_DATABASE_MAX_OPEN_CONNS: 20
      QUOTESVC_DATABASE_MAX_IDLE_CONNS: 10
      QUOTESVC_REDIS_ADDR: redis:6380
      QUOTESVC_EXTERNAL_API_KEY: ${QUOTESVC_EXTERNAL_API_KEY:-ignored}
      QUOTESVC_EXTERNAL_TIMEOUT_SEC: 5
    ports:
      - "8080:8080"

    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/healthz >/dev/null 2>&1 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30

  db:
    image: postgres:18.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: quotesdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d quotesdb"]
      interval: 5s
      timeout: 3s
      retries: 30

  redis:
    image: redis:8.4.0-alpine
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "6380:6380"
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6380", "PING"]
      interval: 5s
      timeout: 3s
      retries: 30

volumes:
  pgdata: