server:
  port: 8080
  serve_swagger: true
  serve_asynqmon: true

database:
  host: db
  port: 5432
  user: postgres
  password: postgres
  name: quotesdb
  sslmode: disable

redis:
  asynq_addr: "redis_asynq:6380"
  cache_addr: "redis_cache:6381"

exchangerate_host:
  base_url: "https://api.exchangerate.host"
  api_key: ""
  timeout_sec: 5

frankfurter:
  base_url: "https://api.frankfurter.dev/v1"
  timeout_sec: 5

worker:
  concurrency: 1
  max_retry: 3
  timeout_sec: 30
  check_interval_sec: 5

cache:
  latest_price_ttl_sec: 600
  exchange_provider_price_ttl_sec: 300
