server:
  port: 8080
  serve_swagger: true

database:
  host: db
  port: 5432
  user: postgres
  password: postgres
  name: quotesdb
  sslmode: disable

redis:
  asynq_addr: "redis_asynq:6380"
  cache_addr: "redis_cache:6381"

external:
  provider: exchangerate_host
  base_url: https://api.exchangerate.host
  api_key: ""
  timeout_sec: 5

worker:
  concurrency: 1

cache:
  ttl_sec: 600
  task_max_retry: 3
  task_timeout_sec: 30